/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.etcsoftworks.smartsneak;


import org.bukkit.plugin.java.JavaPlugin;

import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.ProtocolManager;
import com.etcsoftworks.smartsneak.listeners.server.EntityMetadataListener;


public class SmartSneak extends JavaPlugin {

	private ProtocolManager protocolManager;
	
	public void onEnable() {
		protocolManager = ProtocolLibrary.getProtocolManager();
		
		protocolManager.addPacketListener(new EntityMetadataListener(this));
	}
	
	public void onDisable() {
	}
}
