/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.etcsoftworks.smartsneak;

import com.etcsoftworks.smartsneak.SmartSneak;

import org.junit.Test;
import static org.junit.Assert.*;

public class SmarkSneakTest {
//    @Test public void testSomeLibraryMethod() {
//        SmartSneak classUnderTest = new SmartSneak();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
}
